Feature/2 0 0 build prettier
indiana-university/rivet-react pull request #303
Opened 2022-11-04 20:26 UTC by ri-pandey

2022-11-07 14:43 UTC, burnumd requested changes

2022-11-09 14:23 UTC, ri-pandey commented on package.json
> +    "pretty-quick": "^3.1.3",
Thanks. I updated the rest of the dependencies to use exact versions as well - since it's a trivial change.

2022-11-09 14:45 UTC, burnumd approved these changes

2022-11-09 15:11 UTC, merged

2023-07-19 20:24 UTC, iu-deployer commented
:tada: This PR is included in version 2.0.0-alpha.1 :tada:

The release is available on [GitHub release](https://github.com/indiana-university/rivet-react/releases/tag/v2.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: