feat: 2.0.0 Grid components
indiana-university/rivet-react pull request #336
Opened 2022-12-27 17:41 UTC by athill

2023-01-03 21:43 UTC, burnumd requested changes
Aside from a few documentation typos this looks good

2023-01-03 21:43 UTC, burnumd commented on src/components/Grid/Col.jsx
> + * Use the row component inside a Container to create a grid row
```suggestion
 * Use the col component inside a Container to create a grid column
```

2023-01-03 21:43 UTC, burnumd commented on src/components/Grid/Row.jsx
> + * Generate the a spacing class for this row
```suggestion
 * Generate a spacing class for this row
```

2023-01-06 19:11 UTC, athill commented on src/components/Grid/Col.jsx
> + * Use the row component inside a Container to create a grid row
Fixed. Thanks!

2023-01-06 19:12 UTC, athill commented on src/components/Grid/Row.jsx
> + * Generate the a spacing class for this row
Fixed. Thanks!

2023-01-09 22:01 UTC, burnumd approved these changes

2023-01-17 20:14 UTC, merged

2023-07-19 20:23 UTC, iu-deployer commented
:tada: This PR is included in version 2.0.0-alpha.1 :tada:

The release is available on [GitHub release](https://github.com/indiana-university/rivet-react/releases/tag/v2.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: