fix: 2.0.0 Fix Col tests by renaming width prop that conflicted with Rivetize
indiana-university/rivet-react pull request #346
Opened 2023-01-18 20:49 UTC by athill

2023-01-19 20:23 UTC, burnumd requested changes
Rather than removing the ability to rivetize this component, can we just change the name of the property in this component from `width` to `columnWidth`?

2023-01-20 12:56 UTC, athill commented
@burnumd Fixed. Thanks.

2023-01-25 21:35 UTC, burnumd approved these changes

2023-01-26 19:37 UTC, merged

2023-07-19 20:23 UTC, iu-deployer commented
:tada: This PR is included in version 2.0.0-alpha.1 :tada:

The release is available on [GitHub release](https://github.com/indiana-university/rivet-react/releases/tag/v2.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: