375 - Modified inputs for group functionality.
indiana-university/rivet-react pull request #387
Opened 2023-08-15 20:42 UTC by johglove

2023-08-17 19:40 UTC, burnumd requested changes
As a reminder, commits must follow the [Angular Convention](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for the release process to work

2023-08-21 21:23 UTC, johglove commented
What are the conventions not being followed?

2023-08-21 22:28 UTC, burnumd commented
> What are the conventions not being followed?

This PR, as an example, probably needs to be a `feat: modify inputs for group functionality (#375)`.
If it doesn't have a commit type, it will not trigger a release and the commit will not be included in the release notes.

2023-09-28 19:38 UTC, burnumd requested changes

2023-09-28 19:38 UTC, burnumd commented on src/components/Input/common.jsx
> +    className: inputClassName(elementName, variant, groupped),
```suggestion
    className: inputClassName(elementName, variant, grouped),
```

2023-09-28 19:38 UTC, burnumd commented on src/components/Input/common.jsx
> +      {!groupped && inputElement}
```suggestion
      {!grouped && inputElement}
```

2023-10-19 19:39 UTC, burnumd approved these changes

2023-10-24 15:41 UTC, merged

2023-10-26 18:49 UTC, iu-deployer commented
:tada: This PR is included in version 2.0.0-alpha.5 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/rivet-react/v/2.0.0-alpha.5)
- [GitHub release](https://github.com/indiana-university/rivet-react/releases/tag/v2.0.0-alpha.5)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: