Feature/368/avatar
indiana-university/rivet-react pull request #388
Opened 2023-08-16 21:06 UTC by johglove

2023-08-17 17:21 UTC, burnumd requested changes

2023-08-17 17:21 UTC, burnumd commented on src/components/PageContent/Avatar/Avatar.jsx
> +  }
I'm not sure this array placeholder is necessary. The `classNames` library can handle null/undefined values pretty well.

2023-08-17 17:21 UTC, burnumd commented on src/components/PageContent/Avatar/Avatar.jsx
> +  size: PropTypes.oneOfType([PropTypes.array, PropTypes.oneOf([...Sizes])]),
```suggestion
  size: PropTypes.oneOfType([PropTypes.arrayOf(PropTypes.oneOf(Sizes)), PropTypes.oneOf(Sizes)]),
```

2023-08-17 17:21 UTC, burnumd commented on src/components/PageContent/Avatar/Avatar.jsx
> +export const Sizes = [...AvatarSize, ...AvatarResp];
Did you export sizes with the intent to use it in the tests/documentation to indicate that end-users can use the pre-generated sizes?

2023-08-17 17:21 UTC, burnumd commented on src/components/PageContent/Avatar/Avatar.jsx
> +export const Sizes = [...AvatarSize, ...AvatarResp];
Only components should be capitalized
```suggestion
const avatarSize = [
  "xs",
  "sm",
  "md",
  "lg",
  "xl"
];
const avatarResp = ["sm-up", "md-up", "lg-up", "xl-up", "xxl-up"]
  .map((r) => avatarSize.map((s) => `${s}-${r}`))
  .flat(1);
export const sizes = [...avatarSize, ...avatarResp];
```

2023-08-17 19:39 UTC, burnumd commented
As a reminder, commits must follow the [Angular Convention](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for the release process to work

2023-08-21 21:23 UTC, johglove commented
What are the conventions not being followed?

2023-11-20 16:49 UTC, burnumd approved these changes

2023-11-20 20:53 UTC, merged

2023-11-20 20:59 UTC, iu-deployer commented
:tada: This PR is included in version 2.0.0-alpha.10 :tada:

The release is available on:
- [npm package (@alpha dist-tag)](https://www.npmjs.com/package/rivet-react/v/2.0.0-alpha.10)
- [GitHub release](https://github.com/indiana-university/rivet-react/releases/tag/v2.0.0-alpha.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: